### ISSUE TITLE
Slow animations

### ISSUE THREAD

**Issue by Lignum** [incinirate/Riko4#8] opened 2017-06-03 09:39 UTC
For example, the menu animation in edit takes 20s to complete for me. I'm running at around 2700fps.

You don't seem to be doing any timing in your game loop, which would definitely be the issue if I'm right.

**Comment by incinirate** [comment] 2017-06-03 16:11
Yeah this is a very strange issue, as you pointed out I don't do any correction for actual time, all the timing for animations is based on frames, so having such a high fps should make the animations faster right? Weird stuff, I have reproduced this and am looking into it now.

**Comment by Lignum** [comment] 2017-06-04 09:57
You should make a proper game loop, [this](http://gameprogrammingpatterns.com/game-loop.html) is a good read.

**Comment by incinirate** [comment] 2017-06-05 00:23
Turns out that the issue was due to os.clock being broken on linux based operating systems, this is fixed in 15a64d4

**Closed as completed** 2017-06-05 00:24 UTC

**Comment by Lignum** [comment] 2017-06-05 10:08
I confirm the fixing of this
